version: '3.1'

services:
  app:
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DBNAME: teestdb
    build: .
    ports:
      - 8090:3030
    links:
     - db
    networks:
      - devcode
  db:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_DATABASE=teestdb
    - MYSQL_USER=akhmad
    - MYSQL_PASSWORD=example
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - devcode
  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    links:
      - db
    networks:
      - devcode
networks:
  devcode:
    name: devcode
    driver: bridge